name: Tests

permissions:
  contents: write

on:
  pull_request

jobs:
    run-tests:
        runs-on: ubuntu-latest

        services:
          redis:
            image: redis:7.4
            ports:
              - 6379:6379
          mysql:
            image: mysql:8.0
            ports:
              - 3306:3306
            env:
              MYSQL_DATABASE: pest-driven-laravel
              MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Setup
              uses: ./.github/actions/setup
              with:
                php-version: '8.3'
                php-extensions: 'json, dom, curl, libxml, mbstring'

            - name: Install Dependencies
              run: composer install -q --no-interaction

            - name: Prep application
              run: |
                cp .env.example .env
                php artisan key:generate

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install NPM dependencies
              run: npm install

            - name: Build assets with Vite
              run: npm run build

            - name: Run Tests
              run: php artisan test --compact --coverage --min=75
            
        