name: Tests

permissions:
  contents: write

on:
  pull_request

jobs:
    run-tests:
        runs-on: ubuntu-latest

        services:
          redis:
            image: redis:7.4
            ports:
              - 6379:6379
          mysql:
            image: mysql:8.0
            ports:
              - 3306:3306
            env:
              MYSQL_DATABASE: pest-driven-laravel
              MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Setup cache environment
              id: extcache
              uses: shivammathur/cache-extensions@v1
              with:
                php-version: '8.3'
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr
                key: extension-cache-v1

            - name: Cache extensions
              uses: actions/cache@v4
              with:
                path: ${{ steps.extcache.outputs.dir }}
                key: ${{ steps.extcache.outputs.key }}
                restore-keys: ${{ steps.extcache.outputs.key }}

            - name: Setup PHP and Composer
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'
                tools: composer:v2
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp, :php-psr

            - name: Cache dependencies
              uses: actions/cache@v4.2.1
              with:
                key: composer-cache-${{ hashFiles('**/composer.lock') }}
                path: vendor/

            - name: Install Dependencies
              run: composer install -q --no-interaction

            - name: Prep application
              run: |
                cp .env.example .env
                php artisan key:generate

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install NPM dependencies
              run: npm install

            - name: Build assets with Vite
              run: npm run build

            - name: Run Tests
              run: php artisan test --compact
            
        